# -*- coding: utf-8 -*-
"""estacoes_edit.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11YD4HlaqCbKbXTLxEE61Al_qUgHI54hQ
"""

pip install geopandas

import pandas as pd

# Nome do arquivo CSV
nome_arquivo = 'estacoes.csv'

# Carrega o arquivo CSV em um DataFrame
df = pd.read_csv(nome_arquivo, sep = ';')

# Modifica as colunas 'lat' e 'long'
df['lat'] = df['lat'].apply(lambda x: str(x)[:3] + '.' + str(x)[3:])
df['long'] = df['long'].apply(lambda x: str(x)[:3] + '.' + str(x)[3:])

estacoes = "estacoes_ponto.csv"
df.to_csv(estacoes, index=False, sep=';')

print(df)
#from google.colab import files
#files.download("estacoes_ponto.csv")

import matplotlib.pyplot as plt
import folium
import geopandas as gpd

# Nome do arquivo CSV
nome_arquivo = 'estacoes_ponto.csv'

# Carrega o arquivo CSV em um DataFrame
df = pd.read_csv(nome_arquivo, sep = ';')

# Extrai as colunas de latitude e longitude
latitude = df['lat']
longitude = df['long']


gdf = gpd.GeoDataFrame(df, geometry=gpd.points_from_xy(df['long'], df['lat']))
geojson = "estacoes.geojson"
gdf.to_file(geojson, driver='GeoJSON')

from google.colab import files
files.download(geojson)

# Cria um mapa
mapa = folium.Map()

# Itera sobre as linhas do DataFrame
for _, row in df.iterrows():
    # Obtém as coordenadas de latitude e longitude
    lat = float(row['lat'])
    lon = float(row['long'])

    # Adiciona um marcador ao mapa
    folium.Marker(location=[lat, lon]).add_to(mapa)

# Exibe o mapa
mapa

